name: Chromatic

on:
  push:
    branches: ["*"]
  pull_request:
    types: [ready_for_review, opened, reopened, auto_merge_enabled]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
          cache: "yarn"

      - name: Install
        shell: bash
        run: yarn

      - run: yarn codegen

      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
